import { Inter } from "next/font/google";
import "./globals.css";
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';  
import 'primereact/resources/primereact.css';
import 'primereact/resources/themes/lara-dark-indigo/theme.css';
import { PrimeReactProvider } from "primereact/api";
import { SkeletonTheme } from "react-loading-skeleton";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SkeletonTheme baseColor="#202020" highlightColor="#444">
          <PrimeReactProvider>
            {children}
          </PrimeReactProvider>
        </SkeletonTheme>
      </body>
    </html>
  );
}
